version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "pipelines/kubernetes/hello-kubernetes/deploy/dockerfile/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "npm"
    directory: "pipelines/kubernetes/hello-kubernetes/deploy/dockerfile/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "npm"
