---
mode: ContinuousDeployment
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
branches:
  master:
    label: ''
    increment: Patch
    regex: "^master$|^main$"
  develop:
    label: '{BranchName}'
    increment: Patch
  pull-request:
    label: '{BranchName}'
    increment: Patch
ignore:
  sha: []
merge-message-formats: {}
