---

image:
  pullPolicy: Always
  tag: TAG
env:
  MESSAGE: "Hello world app deployed on Kubernetes!"
  VAULT_ADDR: "http://127.0.0.1:8200"
  # checkov:skip=CKV_SECRET_6
  VAULT_SECRET_PATH: secret/hello-kubernetes
  # checkov:skip=CKV_SECRET_6
resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 128Mi

consulTemplate:
  enabled: true
  pki_backend_role: "pki_int/issue/test"
  env:
    VAULT_ADDR: "http://127.0.0.1:8200"

consulTemplateInit:
  env:
    VAULT_ADDR: "http://vault.internal:8200"
    VAULT_ROLE: "hello-kubernetes"

proxy:
  enabled: true

vaultAgent:
  enabled: true
  role: hello-kubernetes
  secret_path: secret/hello-kubernetes
  env:
    VAULT_ADDR: "http://vault.internal:8200"
    VAULT_SKIP_VERIFY: "true"

ingress:
  enabled: true
  ingressClassName: internal
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    external-dns.alpha.kubernetes.io/hostname: hello-kubernetes.internal.
    external-dns.alpha.kubernetes.io/ttl: "60"
  host: hello-kubernetes.internal

hpa:
  enabled: true
