{{ define "hello-kubernetes.proxy" }}
- name: proxy
  image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
  imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
  lifecycle:
    preStop:
      exec:
        command: ["/bin/sleep", "15"]
  startupProbe:
    httpGet:
      path: /healthz
      port: {{ .Values.proxy.port }}
      scheme: HTTPS
    initialDelaySeconds: 7
    failureThreshold: 5
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /healthz
      port: {{ .Values.proxy.port }}
      scheme: HTTPS
    initialDelaySeconds: 7
    failureThreshold: 1
    periodSeconds: 10
  {{- if .Values.proxy.resources }}
  resources:
    {{- toYaml .Values.proxy.resources | nindent 4 }}
  {{- end }}
  volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
    - name: proxy-config
      mountPath: /usr/local/openresty/nginx/conf/nginx.conf
      subPath: nginx.conf
{{- end }}
