{{- if .Values.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    {{- range .Values.httpRoute.rules }}
      {{- if .matches }}
    - matches:
        {{- toYaml .matches | nindent 8 }}
      {{- end }}
      {{- if .filters }}
      filters:
        {{- toYaml .filters | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "hello-kubernetes.serviceName" $ }}
          port: {{ $.Values.service.port }}
      {{- if and $.Values.rollouts.enabled (eq $.Values.rollouts.strategy "canary") }}
        - name: {{ include "hello-kubernetes.canaryServiceName" $ }}
          port: {{ $.Values.service.port }}
      {{- end }}
    {{- end }}
{{- end }}
