{{- if and .Values.rollouts.enabled (eq .Values.rollouts.strategy "blueGreen") }}
{{- $serviceName := include "hello-kubernetes.previewServiceName" . -}}
---
{{- include "hello-kubernetes.service" (dict
  "serviceName" $serviceName
  "Values" .Values
  "Release" .Release
  "Chart" .Chart)
-}}
{{- end }}
