{{- $serviceName := include "hello-kubernetes.serviceName" . -}}
---
{{- include "hello-kubernetes.service" (dict
  "serviceName" $serviceName
  "Values" .Values
  "Release" .Release
  "Chart" .Chart)
-}}
