{{- if .Values.rollouts.enabled }}
{{- $serviceName := include "hello-kubernetes.rolloutServiceName" . -}}
---
{{- include "hello-kubernetes.service" (dict
  "serviceName" $serviceName
  "Values" .Values
  "Release" .Release
  "Chart" .Chart)
-}}
{{- end }}
