# Default values for hello-kubernetes application

replicaCount: 2

image:
  repository: centos7.internal:5000/hello-kubernetes
  tag: ""
  pullPolicy: IfNotPresent

container:
  port: 8080

env: {}

resources: {}

psp:
  enabled: false

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  capabilities:
    drop:
      - all
    add:
      - IPC_LOCK   # required for vault binary
  seccompProfile:
    type: RuntimeDefault

vaultAgent:
  enabled: false
  image:
    repository: vault
    tag: "1.12.1"
    pullPolicy: Always
  role: ""
  env: {}
  resources:
    requests:
      cpu: 20m
      memory: 20Mi
    limits:
      cpu: 70m
      memory: 32Mi

consulTemplate:
  enabled: false
  image:
    repository: constantin07/consul-template
    tag: 0.29.5
    pullPolicy: Always
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 60m
      memory: 96Mi

proxy:
  enabled: false
  image:
    repository: constantin07/docker-nginx-proxy
    tag: 0.0.1
    pullPolicy: Always
  port: 8443

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  host: chart-example.local
  path: /

hpa:
  enabled: true
  maxReplicas: 4
