---
# Default values for hello-kubernetes application

# -- Number of pods to deploy
replicaCount: 2

image:
  repository: constantin07/hello-kubernetes
  tag: 0.0.1
  pullPolicy: Always

container:
  port: 8080

env: {}

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault

vaultAgent:
  enabled: false
  image:
    repository: vault
    tag: 1.15.2
    pullPolicy: Always
  role: ""
  env: {}
  resources:
    requests:
      cpu: 20m
      memory: 20Mi
    limits:
      cpu: 70m
      memory: 32Mi

consulTemplate:
  enabled: false
  image:
    repository: constantin07/consul-template
    tag: 0.32.0
    pullPolicy: Always
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 60m
      memory: 96Mi

proxy:
  enabled: false
  image:
    repository: constantin07/docker-nginx-proxy
    tag: 0.0.1
    pullPolicy: Always
  port: 8443
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
  host: chart-example.local
  path: /

hpa:
  enabled: true
  maxReplicas: 4
