name: build
run-name: Build docker container

on:
#  pull_request:
#    branches: [ master ]
#    paths:
#      - 'pipelines/kubernetes/hello-kubernetes/deploy/dockerfile/**'
#      - .github/workflows/build.yml

  push:
    paths:
      - 'pipelines/kubernetes/hello-kubernetes/deploy/dockerfile/**'
      - .github/workflows/build.yml
    branches:
      - master
      - develop
    tags: [ '*' ]

  workflow_dispatch:

env:
  IMAGE_REPOSITORY: 'constantin07/hello-kubernetes'

concurrency: build

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    defaults:
      run:
        working-directory: pipelines/kubernetes/hello-kubernetes/deploy/dockerfile
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          # fetch all history for all tags and branches required by GitVersion
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: '5.12.0'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.11.0
        with:
          useConfigFile: true
          configFilePath: pipelines/kubernetes/hello-kubernetes/deploy/GitVersion.yml

      - name: Display version
        run: |
          echo "SemVer: ${{ env.GitVersion_SemVer }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPOSITORY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ecr: false

      - name: Get short commit SHA
        id: var
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          context: pipelines/kubernetes/hello-kubernetes/deploy/dockerfile
          platforms: 'linux/amd64,linux/arm64'
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ steps.var.outputs.short_sha }}
            ${{ env.IMAGE_REPOSITORY }}:${{ env.GitVersion_SemVer }}
          labels: ${{ steps.meta.outputs.labels }}
          load: false

      - name: Buildx load (for Trivy scan)
        run: docker buildx build --load -t ${{ env.IMAGE_REPOSITORY }}:${{ env.GitVersion_SemVer }} .

      - name: Run trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REPOSITORY }}:${{ env.GitVersion_SemVer }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Docker push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ${{ env.IMAGE_REPOSITORY }}:${{ steps.var.outputs.short_sha }} .
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ${{ env.IMAGE_REPOSITORY }}:${{ env.GitVersion_SemVer }} .
