name: Build app container

on:
  pull_request:
    types: [opened, synchronize, reopened] # Don't trigger on PR close/merge
    branches:
      - master
    paths:
      - 'pipelines/kubernetes/hello-kubernetes/deploy/dockerfile/**'
      - .github/workflows/build.yml

  push:
    paths:
      - 'pipelines/kubernetes/hello-kubernetes/deploy/dockerfile/**'
      - .github/workflows/build.yml
    branches:
      - master

  workflow_dispatch:

env:
  IMAGE_REPOSITORY: 'constantin07/hello-kubernetes'
  PLATFORMS: 'linux/amd64,linux/arm64'

permissions: read-all

concurrency: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

jobs:
  determine-version:
    uses: ./.github/workflows/determine-version.yml
    with:
      targetPath: pipelines/kubernetes/hello-kubernetes/deploy/

  build:
    needs: [determine-version]
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      contents: write  # Allow to push tags
    defaults:
      run:
        working-directory: pipelines/kubernetes/hello-kubernetes/deploy/dockerfile
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Check if tag already exists
        id: check
        run: |
          NEXT_VERSION="${{ needs.determine-version.outputs.next_version }}"
          echo "NEXT_VERSION=$NEXT_VERSION" >> "$GITHUB_ENV"

          TAG_EXISTS=$(git ls-remote --tags origin "refs/tags/$NEXT_VERSION" | wc -l)
          echo "exists=$TAG_EXISTS" >> "$GITHUB_OUTPUT"
          if [[ $TAG_EXISTS -gt 0 ]]; then
            echo "❌ Tag $NEXT_VERSION already exists. Failing."
            exit 1
          else
            echo "✅ Tag $NEXT_VERSION does not exist. Proceeding."
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.IMAGE_REPOSITORY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ecr: false

      - name: Docker build
        uses: docker/build-push-action@v7
        with:
          context: pipelines/kubernetes/hello-kubernetes/deploy/dockerfile
          platforms: "${{ env.PLATFORMS }}"
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_REPOSITORY }}:${{ env.NEXT_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          load: false

      - name: Buildx load (for Trivy scan)
        run: docker buildx build --load -t ${{ env.IMAGE_REPOSITORY }}:${{ env.NEXT_VERSION }} .

      - name: Run trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_REPOSITORY }}:${{ env.NEXT_VERSION }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4.37.6
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Docker push
        run: |
          docker buildx build --platform "${{ env.PLATFORMS }}" --push -t ${{ env.IMAGE_REPOSITORY }}:${{ env.NEXT_VERSION }} .

      - name: Push tag
        if: github.ref_name == 'master' && steps.check.outputs.exists == '0'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $NEXT_VERSION
          git push origin ${{ env.NEXT_VERSION }}

  deploy-dev:
    needs: [determine-version, build]
    runs-on: ubuntu-24.04
    environment:
      name: dev
    permissions:
      contents: write  # Allow write version in ArcoCD dev repo
    steps:
      - name: Get GitHub App token
        id: gh-app-auth
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.GH_APP_CLIENT_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: 'Constantin07'
          repositories: argocd-dev
          permission-contents: write

      - name: Checkout ArgoCD env repo
        uses: actions/checkout@v7
        with:
          repository: Constantin07/argocd-dev
          token: ${{ steps.gh-app-auth.outputs.token }}

      - name: Get version
        env:
          VERSION: "${{ needs.determine-version.outputs.next_version }}"
        run: |
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "$VERSION"
          
      - name: Update Helm dependency version
        run: |
          yq -i '(.dependencies[] | select(.name == "simple-k8s-app").version) = strenv(VERSION)' simple-k8s-app/Chart.yaml

      - name: Show change
        run: git diff -- simple-k8s-app/Chart.yaml

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add simple-k8s-app/Chart.yaml

          git diff --cached --quiet && {
            echo "No changes to commit"
            exit 0
          }

          git commit -m "chore: Bump simple-k8s-app to ${{ env.VERSION }}"
          git push

  release:
    needs: [determine-version, deploy-dev]
    # if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0    # Fetch full history
          fetch-tags: true  # Fetch tags too

      - name: Get version
        env:
          VERSION: "${{ needs.determine-version.outputs.next_version }}"
        run: |
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "$VERSION"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --current
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Set up git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$VERSION" \
            --title="Release $VERSION" \
            --repo="$GITHUB_REPOSITORY" \
            --notes-file=CHANGELOG.md \
            --latest \
            --verify-tag
