name: checkov
run-name: Run infra static code analysis

on:
  pull_request:
  workflow_dispatch:

jobs:
  Check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pipelines/kubernetes/hello-kubernetes/deploy
    steps:
      - uses: actions/checkout@v3

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: helm
          skip_check: CKV_K8S_43,CKV_K8S_21
          var-file: ./values.yaml
          output_format: sarif
          output_file_path: results.sarif
          soft_fail: true

      - name: Upload Checkov results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'results.sarif'
