name: checkov

on:

  pull_request:
    paths:
      - 'pipelines/kubernetes/hello-kubernetes/deploy/**'
      - .github/workflows/checkov.yml
      - .checkov.yaml
    branches: [ "master" ]

  push:
    paths:
      - 'pipelines/kubernetes/hello-kubernetes/deploy/**'
      - .github/workflows/checkov.yml
      - .checkov.yaml
    branches: [ "master" ]

  workflow_dispatch:

permissions: read-all

jobs:
  checkov:
    runs-on: ubuntu-24.04
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          config_file: .checkov.yaml
          var_file: pipelines/kubernetes/hello-kubernetes/deploy/values.yaml
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Remove skipped checks from SARIF report
        run: |
          jq '.runs[0].results |= map(select(.suppressions | map(.kind) | index("inSource") | not))' results.sarif > filtered-results.sarif

      - name: Upload Checkov results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: 'filtered-results.sarif'
