name: code-scan
run-name: Code Scanning - Action

on:

  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

  push:

  workflow_dispatch:

jobs:
  CodeQL-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL tools for scanning
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
