name: Workflow1
run-name: Testing out GitHub Actions
on:
  push:
    branches: [ "master" ]

jobs:
  Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
